# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eit_model/pyvista_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.slider_z = QtWidgets.QSlider(self.centralwidget)
        self.slider_z.setMinimum(1)
        self.slider_z.setSingleStep(1)
        self.slider_z.setProperty("value", 50)
        self.slider_z.setOrientation(QtCore.Qt.Vertical)
        self.slider_z.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_z.setTickInterval(5)
        self.slider_z.setObjectName("slider_z")
        self.gridLayout.addWidget(self.slider_z, 2, 0, 1, 1)
        self.slider_x = QtWidgets.QSlider(self.centralwidget)
        self.slider_x.setMinimum(1)
        self.slider_x.setProperty("value", 50)
        self.slider_x.setOrientation(QtCore.Qt.Vertical)
        self.slider_x.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_x.setTickInterval(5)
        self.slider_x.setObjectName("slider_x")
        self.gridLayout.addWidget(self.slider_x, 0, 0, 1, 1)
        self.slider_y = QtWidgets.QSlider(self.centralwidget)
        self.slider_y.setMinimum(1)
        self.slider_y.setSingleStep(1)
        self.slider_y.setProperty("value", 50)
        self.slider_y.setOrientation(QtCore.Qt.Vertical)
        self.slider_y.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_y.setTickInterval(5)
        self.slider_y.setObjectName("slider_y")
        self.gridLayout.addWidget(self.slider_y, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 2, 1, 1)
        self.slice_layout = QtWidgets.QGridLayout()
        self.slice_layout.setObjectName("slice_layout")
        self.gridLayout_2.addLayout(self.slice_layout, 1, 1, 1, 1)
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.gridLayout_2.addLayout(self.main_layout, 1, 0, 1, 1)
        self.eit_model_name = QtWidgets.QLineEdit(self.centralwidget)
        self.eit_model_name.setObjectName("eit_model_name")
        self.gridLayout_2.addWidget(self.eit_model_name, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMesh = QtWidgets.QMenu(self.menubar)
        self.menuMesh.setObjectName("menuMesh")
        self.menuSlicing = QtWidgets.QMenu(self.menuMesh)
        self.menuSlicing.setObjectName("menuSlicing")
        self.menuColormap = QtWidgets.QMenu(self.menuMesh)
        self.menuColormap.setObjectName("menuColormap")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuDebug = QtWidgets.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        self.menuSlicing_2 = QtWidgets.QMenu(self.menubar)
        self.menuSlicing_2.setObjectName("menuSlicing_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_mesh_refresh = QtWidgets.QAction(MainWindow)
        self.action_mesh_refresh.setObjectName("action_mesh_refresh")
        self.action_mesh_show_electrodes = QtWidgets.QAction(MainWindow)
        self.action_mesh_show_electrodes.setObjectName("action_mesh_show_electrodes")
        self.action_slicing_set_slices = QtWidgets.QAction(MainWindow)
        self.action_slicing_set_slices.setObjectName("action_slicing_set_slices")
        self.action_mesh_dynamic_slicing_x = QtWidgets.QAction(MainWindow)
        self.action_mesh_dynamic_slicing_x.setObjectName("action_mesh_dynamic_slicing_x")
        self.action_slicing_z_slicing = QtWidgets.QAction(MainWindow)
        self.action_slicing_z_slicing.setObjectName("action_slicing_z_slicing")
        self.action_new_data = QtWidgets.QAction(MainWindow)
        self.action_new_data.setObjectName("action_new_data")
        self.action_view_xy_plane = QtWidgets.QAction(MainWindow)
        self.action_view_xy_plane.setObjectName("action_view_xy_plane")
        self.action_view_xz_plane = QtWidgets.QAction(MainWindow)
        self.action_view_xz_plane.setObjectName("action_view_xz_plane")
        self.action_view_yz_plane = QtWidgets.QAction(MainWindow)
        self.action_view_yz_plane.setObjectName("action_view_yz_plane")
        self.action_onoff_parallel_projection = QtWidgets.QAction(MainWindow)
        self.action_onoff_parallel_projection.setObjectName("action_onoff_parallel_projection")
        self.action_mesh_reset = QtWidgets.QAction(MainWindow)
        self.action_mesh_reset.setObjectName("action_mesh_reset")
        self.actionremove = QtWidgets.QAction(MainWindow)
        self.actionremove.setObjectName("actionremove")
        self.action3_1 = QtWidgets.QAction(MainWindow)
        self.action3_1.setObjectName("action3_1")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action_show_slice_x = QtWidgets.QAction(MainWindow)
        self.action_show_slice_x.setCheckable(True)
        self.action_show_slice_x.setObjectName("action_show_slice_x")
        self.action_show_slice_y = QtWidgets.QAction(MainWindow)
        self.action_show_slice_y.setObjectName("action_show_slice_y")
        self.action_show_slice_z = QtWidgets.QAction(MainWindow)
        self.action_show_slice_z.setObjectName("action_show_slice_z")
        self.action_slicing_reset_origin = QtWidgets.QAction(MainWindow)
        self.action_slicing_reset_origin.setObjectName("action_slicing_reset_origin")
        self.action_mesh_dynamic_slicing_y = QtWidgets.QAction(MainWindow)
        self.action_mesh_dynamic_slicing_y.setObjectName("action_mesh_dynamic_slicing_y")
        self.action_mesh_dynamic_slicing_z = QtWidgets.QAction(MainWindow)
        self.action_mesh_dynamic_slicing_z.setObjectName("action_mesh_dynamic_slicing_z")
        self.actionvir = QtWidgets.QAction(MainWindow)
        self.actionvir.setObjectName("actionvir")
        self.menuFile.addAction(self.action_exit)
        self.menuSlicing.addAction(self.action_mesh_dynamic_slicing_x)
        self.menuSlicing.addAction(self.action_mesh_dynamic_slicing_y)
        self.menuSlicing.addAction(self.action_mesh_dynamic_slicing_z)
        self.menuMesh.addAction(self.action_mesh_reset)
        self.menuMesh.addAction(self.action_mesh_refresh)
        self.menuMesh.addAction(self.action_mesh_show_electrodes)
        self.menuMesh.addAction(self.menuSlicing.menuAction())
        self.menuMesh.addAction(self.menuColormap.menuAction())
        self.menuView.addAction(self.action_view_xy_plane)
        self.menuView.addAction(self.action_view_xz_plane)
        self.menuView.addAction(self.action_view_yz_plane)
        self.menuView.addSeparator()
        self.menuView.addAction(self.action_onoff_parallel_projection)
        self.menuView.addAction(self.action_show_slice_x)
        self.menuView.addAction(self.action_show_slice_y)
        self.menuView.addAction(self.action_show_slice_z)
        self.menuDebug.addAction(self.action_new_data)
        self.menuSlicing_2.addAction(self.action_slicing_reset_origin)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMesh.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSlicing_2.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuMesh.setTitle(_translate("MainWindow", "Mesh"))
        self.menuSlicing.setTitle(_translate("MainWindow", "Slicing"))
        self.menuColormap.setTitle(_translate("MainWindow", "Color map"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuDebug.setTitle(_translate("MainWindow", "Debug"))
        self.menuSlicing_2.setTitle(_translate("MainWindow", "Slicing"))
        self.action_exit.setText(_translate("MainWindow", "Exit"))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_mesh_refresh.setText(_translate("MainWindow", "Refresh"))
        self.action_mesh_show_electrodes.setText(_translate("MainWindow", "Show electrodes"))
        self.action_slicing_set_slices.setText(_translate("MainWindow", "Set slices"))
        self.action_mesh_dynamic_slicing_x.setText(_translate("MainWindow", "Dynamic slicing X"))
        self.action_slicing_z_slicing.setText(_translate("MainWindow", "Z slicing"))
        self.action_new_data.setText(_translate("MainWindow", "new_data"))
        self.action_view_xy_plane.setText(_translate("MainWindow", "View XY plane"))
        self.action_view_xz_plane.setText(_translate("MainWindow", "View XZ plane"))
        self.action_view_yz_plane.setText(_translate("MainWindow", "View YZ plane"))
        self.action_onoff_parallel_projection.setText(_translate("MainWindow", "Enable parallel projection"))
        self.action_mesh_reset.setText(_translate("MainWindow", "Reset"))
        self.actionremove.setText(_translate("MainWindow", "remove"))
        self.action3_1.setText(_translate("MainWindow", "3|1"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action_show_slice_x.setText(_translate("MainWindow", "Show slice X"))
        self.action_show_slice_y.setText(_translate("MainWindow", "Show slice Y"))
        self.action_show_slice_z.setText(_translate("MainWindow", "Show slice Z"))
        self.action_slicing_reset_origin.setText(_translate("MainWindow", "Reset slice origin"))
        self.action_mesh_dynamic_slicing_y.setText(_translate("MainWindow", "Dynamic slicing Y"))
        self.action_mesh_dynamic_slicing_z.setText(_translate("MainWindow", "Dynamic slicing Z"))
        self.actionvir.setText(_translate("MainWindow", "vir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
